---
abstract: 'A backup application specifically built for backing up files to an IMAP server.'
author:
  - 'Stefan Petrea <stefan.petrea@gmail.com>'
generated_by: 'Dist::Zilla version 1.093140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Backup-Email
requires:
  Alien::wxWidgets: 0
  Archive::Zip: 0
  DBM::Deep: 0
  DateTime: 0
  IO::Socket::SSL: 0
  List::AllUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  MIME::Base64: 0
  MIME::Lite: 0
  Mail::IMAPClient: 0
  Moose: 0
  MooseX::NonMoose: 0
  Net::SMTP::TLS: 0
  Net::SSLeay: 0
  Wx: 0
  YAML: 0
  perl: 5.010000
version: 0.022
